- id: gitfluff-lint
  name: gitfluff (lint)
  description: Lint commit messages using gitfluff
  entry: gitfluff lint
  language: system
  stages: [commit-msg]
  pass_filenames: true
  always_run: true
  minimum_pre_commit_version: "2.9.0"

- id: gitfluff-write
  name: gitfluff (lint + write)
  description: Lint and rewrite commit messages using gitfluff --write
  entry: gitfluff lint --write
  language: system
  stages: [commit-msg]
  pass_filenames: true
  always_run: true
  minimum_pre_commit_version: "2.9.0"
