-   id: gitfluff-lint
    name: gitfluff commit message linter
    description: Enforce Conventional Commits and optional cleanup policies for commit messages.
    entry: gitfluff lint
    language: rust
    types: [text]
    always_run: true
    pass_filenames: true
    stages: [commit-msg]
